#!/usr/bin/env bash
# Creates the local OTA dev key (ECDSA P-256): private PEM, public PEM and a C header for
# -DHN_OTA_DEV_KEY builds. Keeps an existing key unless --force is given.
set -euo pipefail

dir="$(cd "$(dirname "$0")" && pwd)"
priv="$dir/ota-dev.pem"
pub="$dir/ota-dev.pub.pem"
header="$dir/ota-dev.pub.h"

if [[ -f "$priv" && "${1:-}" != "--force" ]]; then
  echo "dev key exists: $priv (use --force to replace it)"
else
  umask 077
  openssl ecparam -name prime256v1 -genkey -noout -out "$priv"
  openssl ec -in "$priv" -pubout -out "$pub" 2>/dev/null
  date +dev-%Y-%m > "$dir/ota-dev.keyid"
  echo "created $priv"
fi
[[ -f "$pub" ]] || openssl ec -in "$priv" -pubout -out "$pub" 2>/dev/null
[[ -f "$dir/ota-dev.keyid" ]] || date +dev-%Y-%m > "$dir/ota-dev.keyid"
key_id="$(cat "$dir/ota-dev.keyid")"

{
  echo "// Generated by tools/dev-keys/make-dev-key.sh. Development builds only, never committed."
  echo "#pragma once"
  echo "#define HN_OTA_DEV_KEY_ID \"$key_id\""
  printf '#define HN_OTA_DEV_KEY_PEM'
  while IFS= read -r line; do printf ' \\\n    "%s\\n"' "$line"; done < "$pub"
  echo
} > "$header"
echo "key id $key_id, header $header"
